### ISSUE TITLE
Problem with mounting VB shared folders

### ISSUE THREAD

**Issue by walldemar** [damianlewis/devbox#2]
Hi!
I tried to use your devbox and i have some error.

"Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o actimeo=1,nolock,uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

  fmask     =<arg> umask of regular files"

I tried with:
vagrant plugin install vagrant-vbguest
vagrant vbguest

and it doesnt help.

VB Guest Additions 5.2.1
VB 5.2.0

Do you know how to fix it?

**Comment by damianlewis** [comment]
Not sure but VirtualBox 5.2 isn't supported by Vagrant, so that may have something to do with it.

Check [here](https://www.vagrantup.com/docs/virtualbox) for supported versions.

**Comment by walldemar** [comment]
I have reinstalled VB to 5.1.3 and it's not working.

**Comment by damianlewis** [comment]
What platform are you on and which version of Vagrant are you using?

Also, can you send your devbox.yaml configuration.
